### ISSUE TITLE
I got this error "Invalid data found when processing input" when i tried to play Tcp-H264 from the App

### ISSUE THREAD

**Issue by chenxi1991** [magicsih/AndroidScreenCaster#1]
![image](https://user-images.githubusercontent.com/13568754/26967648-9a260f64-4d31-11e7-8ad7-ea27cc5df6bf.png)

**Comment by chenxi1991** [comment]
And, does "your IP here" means server's IP?

**Comment by magicsih** [comment]
@chenxi1991 yes. "your IP here" means server's IP where ffmpeg listens on 49152 port. which media format did you choose. it looks like h.264 + tcp combination. is that correct?

**Comment by magicsih** [comment]
Can you pull and retry? I missed color format condition handling.

**Comment by chenxi1991** [comment]
Yes ,h.265 + tcp. Then everything is correct,but it just doesn,t work.I try to Ping the client from the server,and the network is working. so, I totally have no idea .

**Comment by chenxi1991** [comment]
OK , I'll pull and try again now

**Comment by chenxi1991** [comment]
@magicsih Thank you so much, It does work now.

**Comment by magicsih** [comment]
@chenxi1991 Thank you for reporting the issue. 👍

**Comment by NeoxzAI** [comment]
Same issue, I'm using android 7.0, 2 devices tested and didn't works. @magicsih
