### ISSUE TITLE
Dcode error on Android device with MediaCodec

### ISSUE THREAD

**Issue by chenxi1991** [magicsih/AndroidScreenCaster#2]
I try to decode the H.264 on another Android-device with MediaCodec and display on a SurfaceTexture.
Here are my codes on the server:
Init the Decoder:
![image](https://user-images.githubusercontent.com/13568754/27217125-26897fe4-52ab-11e7-8cb7-9e4673d90446.png)
Decode a frame:
![image](https://user-images.githubusercontent.com/13568754/27217154-466e0848-52ab-11e7-9b67-920c6c2d59f3.png)

The decoded result displayed on the SurfaceTexture:
The first frame is normal
![image](https://user-images.githubusercontent.com/13568754/27217281-cd2c5cd6-52ab-11e7-97a8-c5cd3e84c8df.png)
But when I do some operations on the client ,It comes out like that:
![image](https://user-images.githubusercontent.com/13568754/27217352-195d68de-52ac-11e7-86c3-8e31346607fe.png)

I'm so sorry to bother you again! could you give me some advice.

**Comment by magicsih** [comment]
@chenxi1991 Did you find the solution?

**Comment by chenxi1991** [comment]
@magicsih not yet. I still have no idea.

**Comment by chenxi1991** [comment]
@magicsih I tried to set the sps&pps from the first frame's data. But not useful

**Comment by magicsih** [comment]
@chenxi1991 I have no idea either.  I haven't yet implemented decoding part on Android.

**Comment by chenxi1991** [comment]
@magicsih  Thanks anyway. If you need,I'll let u know when I implement it.

**Comment by magicsih** [comment]
@chenxi1991 Please, share the result :) Thanks!

**Comment by chenxi1991** [comment]
@magicsih  I‘ve got it done this afternoon,but the code is messy. after I refactor it I'll push it to my github and give u a link. :)

**Comment by chenxi1991** [comment]
@magicsih Here is the link https://github.com/chenxi1991/ScreenShare
