### ISSUE TITLE
Help: How to manipulate display video

### ISSUE THREAD

**Issue by JayDreamWorld** [magicsih/AndroidScreenCaster#5]
For example, I want to rotate the output screen or make the output screen grayscale. How should I do it?
I saw on the back service, there is only an encoder, and the byte array from outputbuffer is not an image format. Can you point me to the right direction.
Thanks for your time!

**Comment by magicsih** [comment]
I think you can extract a snapshot from the media stream. After that, you can do anything what you want to do with the snapshot. look for media decoders on stream receiver side.
sorry for late reply anyway.
