### ISSUE TITLE
Send sound from microphone

### ISSUE THREAD

**Issue by suiteappdev** [magicsih/AndroidScreenCaster#7]
Hello, 
Can you help me ? How can stream sound from microphone? I want stream screen and microphone audio and send to rmtp server using ffmpeg.

Please help me.

**Comment by magicsih** [comment]
Hello,

So, you want stream screen and microphone audio. 
although I'm not an expert of media streaming maybe you can mix screen casting source and AudioRecord API. 

You can stream user sound via OutputStream to remote endpoint.
Here are good examples.

- https://github.com/aahlenst/android-audiorecord-sample/blob/master/src/main/java/com/example/audiorecord/BluetoothRecordActivity.java
- https://stackoverflow.com/questions/8499042/android-audiorecord-example

**Comment by suiteappdev** [comment]
Thanks.
