### ISSUE TITLE
Android x86 and VP8 doesn't work

### ISSUE THREAD

**Issue by carpiupin** [magicsih/AndroidScreenCaster#9]
Hi!,

I like your app, it works fine with my device, but I was trying to mirror my Android-x86 testing environment and with H264 seems to work but with VP8 it doesn't. There are no errors in Android but ffplay cannot decode, this message appears: "nvalid data found when processing input".

Do you know if I must change something in the encoding configuration when it runs in Android-x86?, or why h264 works fine but vp8 no (both tcp/udp)?

![Captura de pantalla de 2020-09-25 12-30-47](https://user-images.githubusercontent.com/9316828/94257071-0a515380-ff2b-11ea-8568-5958f6caf01a.png)

**Comment by magicsih** [comment]
Did you solve it?
